# Generated by Django 3.0.1 on 2019-12-18 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='name', max_length=30)),
                ('last_name', models.CharField(max_length=60)),
                ('father_name', models.CharField(max_length=30)),
                ('birth_day', models.DateField()),
                ('employ_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('mobile_num', models.CharField(max_length=11)),
                ('phone_num', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=200)),
                ('account_num', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('img', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
