# Generated by Django 3.0.1 on 2019-12-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20191218_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='name', max_length=30)),
                ('last_name', models.CharField(max_length=60)),
                ('father_name', models.CharField(blank=True, max_length=30)),
                ('job_name', models.CharField(max_length=60)),
                ('birth_day', models.DateField()),
                ('mobile_num', models.CharField(max_length=11)),
                ('phone_num', models.CharField(blank=True, max_length=13)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('account_num', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='account_num',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='father_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_num',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
