# Generated by Django 3.0.1 on 2019-12-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20191218_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birth_day',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='job_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.CreateModel(
            name='recive_cheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_amount', models.BigIntegerField()),
                ('income_date', models.DateField()),
                ('recive_date', models.DateField()),
                ('pay_name', models.CharField(choices=[('c', 'carier')], max_length=30)),
                ('status', models.CharField(choices=[('w', 'waiting for income'), ('p', 'pass'), ('i', 'ignore'), ('r', 'waiting for get')], max_length=1)),
                ('customer_name', models.ManyToManyField(to='service.customer')),
            ],
        ),
    ]
