# Generated by Django 3.0.1 on 2019-12-18 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20191219_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recive_cheque',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='recive_cheque',
            name='customer_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='service.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recive_cheque',
            name='pay_name',
            field=models.CharField(max_length=30),
        ),
    ]
