# Generated by Django 3.0.1 on 2019-12-18 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20191219_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('personal_persent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('transaction', models.BigIntegerField()),
                ('cash_pay', models.BigIntegerField()),
                ('duration', models.DurationField()),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.customer')),
                ('person_name', models.ForeignKey(default='no person', on_delete=django.db.models.deletion.SET_DEFAULT, to='service.person')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.product')),
            ],
        ),
    ]
