# Generated by Django 3.0.1 on 2019-12-19 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_contract_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='recive_cheque',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.contract'),
        ),
        migrations.AlterField(
            model_name='recive_cheque',
            name='customer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.customer'),
        ),
    ]
