# Generated by Django 3.0.1 on 2019-12-21 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20191219_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_replay', models.BooleanField()),
                ('is_ticket', models.BooleanField()),
                ('sender', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField()),
                ('subject', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('reciver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.person')),
            ],
        ),
    ]
