# Generated by Django 3.0.1 on 2019-12-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='reciver',
            field=models.CharField(max_length=30),
        ),
    ]
